name: Stats_Angle2Abaltion
channels:
  - defaults
dependencies:
  - python=3.7
  - jupyterlab==2.1.5
  - scipy==1.5.0
  - matplotlib==3.2.2
  - pandas==1.1.3
  - seaborn==0.10.1
  - pip:
    - watermark==2.0.2
